import localFont from "next/font/local";
import "../globals.css";
import Link from "next/link";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <div className="h-screen w-full flex justify-center items-center uppercase font-medium font-mono text-5xl">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
